/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "puzzle.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PieceCommand, PieceCommand, AUTO)


PB_BIND(PuzzleCommand, PuzzleCommand, AUTO)


PB_BIND(Ack, Ack, AUTO)





