/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PUZZLE_PB_H_INCLUDED
#define PB_PUZZLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Status {
    Status_STATUS_OK = 0,
    Status_STATUS_ERROR = 1,
    Status_STATUS_BUSY = 2,
    Status_STATUS_DONE = 3
} Status;

/* Struct definitions */
typedef struct _PieceCommand {
    uint32_t piece_id;
    /* Pick position (where the piece currently is) in mm */
    float pick_x;
    float pick_y;
    /* Place position (where the piece needs to go) in mm */
    float place_x;
    float place_y;
    /* Rotation in degrees */
    float rotation;
} PieceCommand;

typedef struct _PuzzleCommand {
    pb_size_t pieces_count;
    PieceCommand pieces[9];
} PuzzleCommand;

typedef struct _Ack {
    Status status;
    uint32_t piece_id; /* which piece this ack is about (0 = general) */
} Ack;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Status_MIN Status_STATUS_OK
#define _Status_MAX Status_STATUS_DONE
#define _Status_ARRAYSIZE ((Status)(Status_STATUS_DONE+1))



#define Ack_status_ENUMTYPE Status


/* Initializer values for message structs */
#define PieceCommand_init_default                {0, 0, 0, 0, 0, 0}
#define PuzzleCommand_init_default               {0, {PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default, PieceCommand_init_default}}
#define Ack_init_default                         {_Status_MIN, 0}
#define PieceCommand_init_zero                   {0, 0, 0, 0, 0, 0}
#define PuzzleCommand_init_zero                  {0, {PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero, PieceCommand_init_zero}}
#define Ack_init_zero                            {_Status_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PieceCommand_piece_id_tag                1
#define PieceCommand_pick_x_tag                  2
#define PieceCommand_pick_y_tag                  3
#define PieceCommand_place_x_tag                 4
#define PieceCommand_place_y_tag                 5
#define PieceCommand_rotation_tag                6
#define PuzzleCommand_pieces_tag                 1
#define Ack_status_tag                           1
#define Ack_piece_id_tag                         2

/* Struct field encoding specification for nanopb */
#define PieceCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   piece_id,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    pick_x,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    pick_y,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    place_x,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    place_y,           5) \
X(a, STATIC,   SINGULAR, FLOAT,    rotation,          6)
#define PieceCommand_CALLBACK NULL
#define PieceCommand_DEFAULT NULL

#define PuzzleCommand_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  pieces,            1)
#define PuzzleCommand_CALLBACK NULL
#define PuzzleCommand_DEFAULT NULL
#define PuzzleCommand_pieces_MSGTYPE PieceCommand

#define Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, UINT32,   piece_id,          2)
#define Ack_CALLBACK NULL
#define Ack_DEFAULT NULL

extern const pb_msgdesc_t PieceCommand_msg;
extern const pb_msgdesc_t PuzzleCommand_msg;
extern const pb_msgdesc_t Ack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PieceCommand_fields &PieceCommand_msg
#define PuzzleCommand_fields &PuzzleCommand_msg
#define Ack_fields &Ack_msg

/* Maximum encoded size of messages (where known) */
#define Ack_size                                 8
#define PUZZLE_PB_H_MAX_SIZE                     PuzzleCommand_size
#define PieceCommand_size                        31
#define PuzzleCommand_size                       297

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
